# Generated by Django 3.0.7 on 2020-06-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200606_1630'),
        ('app', '0003_auto_20200606_1731'),
    ]

    operations = [
    ]
